version: '3.8'

services:
  db:
    image: ankane/pgvector:latest
    container_name: curate_postgres
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: curate_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d curate_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
